service: bus-lviv-bot
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'development'}
  environment:
    NODE_ENV: ${self:provider.stage}

functions:
  bot:
    handler: bot.handler
    environment:
      BOT_TOKEN: ${ssm:bus_lviv_bot_token, env:BOT_TOKEN}
      API_LOGIN: ${ssm:bus_lviv_bot_api_login, env:API_LOGIN}
      API_PASSWORD: ${ssm:bus_lviv_bot_api_password, env:API_PASSWORD}
    events:
      - http:
          path: bot
          method: post
plugins:
  - serverless-offline
